# Ejemplos de Optimización


### **Ejercicio de maximización rentabilidad por dividendos:**

_Objetivo:_ Maximizar la rentabilidad por dividendos de una cartera teniendo en cuenta que la exposición a moneda extranjera debe ser menos o igual al 33%:

**Activos:**

| Activo | Dividendo | % Ingresos Extranjero |
|--------|-----------|-----------------------|
| SAN    | 3.67%     | 60%                   |
| REE    | 6.8%      | 10%                   |
| BBVA   | 5.6%      | 50%                   |
| REPSOL | 4.54%     | 45%                   |


**Entrega:**
Determinar las proporciones óptimas de inversión para cada activo, calculando la rentabilidad total y la exposición a moneda extranjera.

In [1]:
import numpy as np
import pandas as pd
import cvxpy as cp

In [47]:
# datos almacenados en arrays
dividendos = np.array([3.67, 4.2, 5.6, 5])
ingresos = np.array([60, 10, 50, 25])

In [48]:
# creacion de variables de decisión
pesos = cp.Variable(dividendos.shape[0])

In [49]:
# construcción de función objetivo
objective = cp.sum(cp.multiply(pesos, dividendos))

In [50]:
# lista de expresiones representando las restricciones
constraints = [
    cp.sum(pesos) == 1.0,
    cp.sum(cp.multiply(ingresos, pesos)) <= 40,
    pesos >= 0.0
]

In [51]:
# instancia de un problema en CVXPY
problem = cp.Problem(cp.Maximize(objective), constraints)

In [59]:
# resolución del problema y valor optimo
result = problem.solve()
print(f'La rentabilidad por dividendo obtenida es: {result:.2f}%')

La rentabilidad por dividendo obtenida es: 5.36%


In [54]:
# valor de las variables en el máximo de la función objetivo
pesos.value

array([1.25638459e-10, 6.71469679e-10, 5.99999999e-01, 4.00000000e-01])

In [56]:
pd.Series(100*pesos.value.round(2), index=['SAN', 'REE','BBVA','REPSOL'])

SAN        0.0
REE        0.0
BBVA      60.0
REPSOL    40.0
dtype: float64

### Apartado adicional
- Resolver el problema anterior si además no se puede invertir más del 30% en un solo activo.


In [60]:
# añadimos la nueva restricción
constraints.append(pesos <= 0.3)

In [62]:
# resolución del problema y valor optimo
problem = cp.Problem(cp.Maximize(objective), constraints)
result = problem.solve()
print(f'La rentabilidad por dividendo obtenida es: {result:.2f}%')

La rentabilidad por dividendo obtenida es: 4.81%


In [63]:
pd.Series(100*pesos.value.round(2), index=['SAN', 'REE','BBVA','REPSOL'])

SAN       10.0
REE       30.0
BBVA      30.0
REPSOL    30.0
dtype: float64

---

### **Ejercicio de Optimización de Portafolio con Mínimo Riesgo**

**Objetivo**: Minimizar el riesgo de un portafolio de inversión.

### Datos:
- **Retornos Esperados**: Un array `retornos_esperados` que contiene el retorno esperado para cada activo.
- **Matriz de Covarianza**: `matriz_cov`, describiendo la covarianza entre los activos y el riesgo combinado.


### Restricciones:
1. No se permiten posiciones cortas

Recordad que la varianza de una cartera, $ \sigma^2_p $, se calcula como:

$ \qquad \qquad \sigma^2_p = \mathbf{w}^T \Sigma \mathbf{w} $

donde:
- $ \mathbf{w} $ es el vector de pesos de la cartera. Cada elemento $ w_i $ representa la fracción del capital total invertido en el activo $ i $.
- $ \Sigma $ es la matriz de covarianza de los rendimientos de los activos. Cada elemento $ \sigma_{ij} $ representa la covarianza entre los rendimientos de los activos $ i $ y $ j $.


In [153]:
# Datos de retornos y covarianzas

retornos_esperados = np.array([0.17, 0.10, 0.07, 0.09])  # Ejemplo de retornos esperados
matriz_cov = np.array([[1.83977374, 1.23002575, 1.59282297, 0.69409837],
       [1.23002575, 1.45345954, 1.7548078 , 1.31477996],
       [1.59282297, 1.7548078 , 2.14425197, 1.55568552],
       [0.69409837, 1.31477996, 1.55568552, 1.46502412]])

In [154]:
# Variable de decisión
pesos = cp.Variable(4)

In [155]:
# Función objetivo
riesgo = cp.quad_form(pesos, matriz_cov)
objetivo = cp.Minimize(riesgo)

In [156]:
# Restricciones
constraints = [cp.sum(pesos) == 1, 
               pesos >= 0]

In [157]:
# Problema de optimización
problema = cp.Problem(objetivo, constraints)

# Resolviendo el problema
resultado = problema.solve()

# Resultados
pesos_optimos = pesos.value

In [158]:
print(f'El riesgo de la cartera es: {riesgo.value:.2f}')
print(f'La rentabilidad de la cartera es: {100*(retornos_esperados @ pesos_optimos).round(4)}%')
print(f'Los pesos que hacen que la cartera tenga el menor riesgo son: {100*pesos_optimos.round(2)}')

El riesgo de la cartera es: 1.15
La rentabilidad de la cartera es: 12.22%
Los pesos que hacen que la cartera tenga el menor riesgo son: [40. -0. -0. 60.]


### Apartados adicionales
- Resolver el problema anterior si además quieres una rentabilidad mínima del 14%

In [133]:
constraints.append(retornos_esperados @ pesos >= 0.14)

In [134]:
# Problema de optimización
problema = cp.Problem(objetivo, constraints)

# Resolviendo el problema
resultado = problema.solve()

# Resultados
pesos_optimos = pesos.value

In [91]:
(retornos_esperados @ pesos_optimos).round(4)

0.11

In [135]:
print(f'El riesgo de la cartera es: {riesgo.value:.2f}')
print(f'La rentabilidad de la cartera es: {100*(retornos_esperados @ pesos_optimos).round(4)}%')
print(f'Los pesos que hacen que la cartera tenga el menor riesgo son: {100*pesos_optimos.round(2)}')

El riesgo de la cartera es: 1.25
La rentabilidad de la cartera es: 14.000000000000002%
Los pesos que hacen que la cartera tenga el menor riesgo son: [62. -0. -0. 38.]


- ¿Y si la rentabilidad mínime es del 18%?

In [136]:
# Restricciones
constraints = [cp.sum(pesos) == 1, 
               pesos >= 0,
               retornos_esperados @ pesos >= 0.18]


# Problema de optimización
problema = cp.Problem(objetivo, constraints)

# Resolviendo el problema
resultado = problema.solve()

# Resultados
pesos_optimos = pesos.value

In [137]:
print(f'Los pesos que hacen que la cartera tenga el menor riesgo son: {100*pesos_optimos.round(2)}')

AttributeError: 'NoneType' object has no attribute 'round'

In [101]:
resultado

inf

Las restricciones establecidas en este problema de optimización hacen que no tenga solución.

Dado que el rendimiento más alto de los activos es del 17%, es imposible lograr una rentabilidad del 18% con una cartera formada por estos activos.

---

### **Ejercicio de Optimización de Portafolio con Máxima Rentabilidad dado un Riesgo**

**Objetivo**: Maximizar la rentabilidad de un portafolio de inversión asegurando un riesgo máximo.

### Datos:
- **Retornos Esperados**: Un array `retornos_esperados` que contiene el retorno esperado para cada activo.
- **Matriz de Covarianza**: `matriz_cov`, describiendo la covarianza entre los activos y el riesgo combinado.


### Restricciones:
1. No se permiten posiciones cortas

In [138]:
# Datos de retornos y covarianzas

retornos_esperados = np.array([0.17, 0.10, 0.07, 0.09])  # Ejemplo de retornos esperados
matriz_cov = np.array([[1.83977374, 1.23002575, 1.59282297, 0.69409837],
       [1.23002575, 1.45345954, 1.7548078 , 1.31477996],
       [1.59282297, 1.7548078 , 2.14425197, 1.55568552],
       [0.69409837, 1.31477996, 1.55568552, 1.46502412]])

In [139]:
# Variable de decisión
pesos = cp.Variable(4)

In [140]:
# Función objetivo
rentabilidad = retornos_esperados @ pesos
objetivo = cp.Maximize(rentabilidad)

In [149]:
# Restricciones
riesgo = cp.quad_form(pesos, matriz_cov)

constraints = [cp.sum(pesos) == 1, 
               pesos >= 0,
               riesgo <= 1.20]

riesgo = cp.quad_form(pesos, matriz_cov)

In [150]:
# Problema de optimización
problema = cp.Problem(objetivo, constraints)

# Resolviendo el problema
resultado = problema.solve()

# Resultados
pesos_optimos = pesos.value

In [151]:
resultado

0.13444668904708934

In [152]:
print(f'El riesgo de la cartera es: {riesgo.value:.2f}')
print(f'La rentabilidad de la cartera es: {100*(retornos_esperados @ pesos_optimos).round(4)}%')
print(f'Los pesos que hacen que la cartera tenga el menor riesgo son: {100*pesos_optimos.round(2)}')

El riesgo de la cartera es: 1.20
La rentabilidad de la cartera es: 13.44%
Los pesos que hacen que la cartera tenga el menor riesgo son: [56.  0.  0. 44.]


---

### **Ejercicio de Optimización de Portafolio usando ratio de sharpe**

## Problema de Optimización del Ratio de Sharpe

**Objetivo**: Maximizar el ratio de Sharpe cuadrático de un portafolio de inversión.

### Datos:
- **Retornos Esperados**: Vector `retornos_esperados` con el retorno esperado de cada activo.
- **Matriz de Covarianza**: Matriz `matriz_cov` que representa la covarianza entre los rendimientos de los activos.
- **Tasa Libre de Riesgo**: Valor `tasa_libre_riesgo`, representando la tasa de retorno sin riesgo.

### Solución:
Buscamos los pesos que conforman la cartera con el mayor ratio de Sharpe, optimizando así la relación entre el retorno esperado y la volatilidad del portafolio.


In [109]:
# Datos de ejemplo
retornos_esperados = np.array([0.12, 0.10, 0.07, 0.09])

matriz_cov = np.array([[1.6768397 , 0.66434839, 1.26288857, 1.85128714],
                        [0.66434839, 0.69280958, 0.87199711, 0.55437544],
                        [1.26288857, 0.87199711, 1.92091975, 1.5573455 ],
                        [1.85128714, 0.55437544, 1.5573455 , 2.51120125]])

tasa_libre_riesgo = 0.03

In [110]:
# Variable de decisión
pesos = cp.Variable(4)

In [111]:
# Función objetivo (Ratio de Sharpe)
retorno_portafolio = retornos_esperados @ pesos
volatilidad_portafolio = cp.sqrt(cp.quad_form(pesos, matriz_cov))
ratio_sharpe = (retorno_portafolio - tasa_libre_riesgo) / volatilidad_portafolio

In [112]:
# Restricciones
constraints = [cp.sum(pesos) == 1, pesos >= 0]

In [113]:
# Definición del problema
problema = cp.Problem(cp.Maximize(ratio_sharpe), constraints)

# Intentando resolver el problema
try:
    problema.solve()
except Exception as e:
    print("Error al resolver el problema:", e)

Error al resolver el problema: Problem does not follow DCP rules. Specifically:
The objective is not DCP. Its following subexpressions are not:
power(QuadForm(var710, [[1.68 0.66 1.26 1.85]
 [0.66 0.69 0.87 0.55]
 [1.26 0.87 1.92 1.56]
 [1.85 0.55 1.56 2.51]]), 0.5)
